// ******************************************************************
//       /\ /|       @file       DefAudio.cs
//       \ V/        @brief      auto generated by RabiConfigGenerator. ./Excel/Audio.xlsx
//       | "")       @author     Shadowrabbit, yingtu0401@gmail.com
//       /  |
//      /  \\        @Modified   2022-04-25 13:25:11
//    *(__\_\        @Copyright  Copyright (c)  2022, Shadowrabbit
// ******************************************************************

namespace ExampleProject.Defs
{
    public static class DefAudio
    {
        public static readonly string DUnitOnChain = "UnitOnChain";  //通用连锁
        public static readonly string DUnitOnDie = "UnitOnDie";  //通用死亡
        public static readonly string DHeroOnHit = "HeroOnHit";  //通用英雄受击
        public static readonly string DUnitOnHitStar = "UnitOnHitStar";  //星星受击
        public static readonly string DUnitOnPlaced = "UnitOnPlaced";  //单位放置
    }
}